color: null
fieldLayouts:
  a777d571-67c3-4c47-a13c-cebe6c26bc2d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-14T01:21:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6d792fe4-471d-48ed-bc45-5fe112ba7e46 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3c8a920-eb3a-4580-b31c-d3b585927bc2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-13T03:48:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3e544b8-88bf-4761-8df2-d767fa1502b7 # Text
            handle: headline
            includeInCards: false
            instructions: null
            label: Headline
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d150c205-3963-432d-aeb3-b16c63cd6642
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-13T03:48:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0b199c11-0b79-4e4b-b931-f9c85e23a667 # Link / Button
            handle: null
            includeInCards: false
            instructions: 'If left blank, will include a "back to blog" button'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2cbc401-df36-4f0c-89c1-14a33024b438
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-14T01:17:30+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: fa59b73c-4193-4d7e-a42a-2bda6d535687 # Lightswitch - Default On
            handle: includeCalendly
            includeInCards: false
            instructions: null
            label: 'Include Calendly?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f95b1eb3-05b7-4fa9-829a-859fcd19d287
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9005a201-7385-4446-b2ce-e7a48ca5c730
        userCondition: null
handle: bannerCallout
hasTitleField: false
icon: null
name: 'Banner Callout'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
