color: null
fieldLayouts:
  014c6996-53f1-48cb-94bc-af30bec0a242:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-13T04:47:35+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d974690b-180a-439d-8ac1-36315c41e92f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-14T01:31:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ea602fb0-2096-4803-a74f-8f85795991ce # Featured Blog
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e50570f7-fd49-43b4-8102-6d3def6b7c0b
            userCondition: null
            warning: null
            width: 100
        name: Hero
        uid: fc7d87b4-021d-4f65-989f-96bf0255f50b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-14T01:59:30+00:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'The page builder will start after the blog posts'
            type: craft\fieldlayoutelements\Tip
            uid: 48660c73-2c56-4cc4-ad32-0f337f18e49f
            userCondition: null
          -
            dateAdded: '2025-05-14T01:59:30+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 69b71247-c0c6-4339-b528-2d8b66d72119 # Page Builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 00e6e849-2672-4a61-b708-99370a8e7cf9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 113323f8-f9e8-4dd6-9554-7b990f915d1e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-14T01:31:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 453f9294-407d-405a-b73b-d5b63aec2eaa # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9fbb610-0bef-4f7f-befd-78fef710afe1
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 83db718b-3892-4c4e-ae38-f06afecb4d1c
        userCondition: null
handle: blogListing
hasTitleField: true
icon: table-list
name: 'Blog Listing'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
