color: null
fieldLayouts:
  3f0ebb0b-be29-4133-b44a-8a6cfa156e13:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-13T00:09:59+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3e05d731-bf26-4cee-a50e-f934a288a45d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-13T00:50:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3e544b8-88bf-4761-8df2-d767fa1502b7 # Text
            handle: subheadline
            includeInCards: false
            instructions: null
            label: Subheadline
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2929149c-2a85-4afa-a9b5-ee9e372b46c7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-13T00:52:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6d792fe4-471d-48ed-bc45-5fe112ba7e46 # Image
            handle: featuredImage
            includeInCards: false
            instructions: null
            label: 'Featured Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b55a0ec8-7377-4c5b-99e3-8457a75df220
            userCondition: null
            warning: null
            width: 100
        name: Hero
        uid: d8abfd1b-1377-4c19-8506-fbbfacc83e2a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-13T03:45:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a7852838-0859-4c63-a1a1-4ecfb77a284e # Blog Builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49ece882-f73f-4b7b-bc80-e8c60835959a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 19c14dc8-fc04-4cff-8249-05651539257c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-13T00:50:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6d792fe4-471d-48ed-bc45-5fe112ba7e46 # Image
            handle: thumbnail
            includeInCards: false
            instructions: null
            label: Thumbnail
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc01da1e-b1e2-4069-a83a-add9505051b9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-13T00:50:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 42eea3c2-2f84-43d8-a495-647d4994a8d5 # Text - Multiline
            handle: excerpt
            includeInCards: false
            instructions: null
            label: Excerpt
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fab41fe4-4faf-4c35-b35b-1b46e9bd6bcd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-13T00:50:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8591badb-f584-4d11-8886-8e8e01957bae # Blog Categories
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f5735b0f-9c1a-4516-86b3-cbf4735dd73d
            userCondition: null
            warning: null
            width: 100
        name: Listing
        uid: 89b085cf-714b-4163-aa15-ad05d2592451
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-13T00:50:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 453f9294-407d-405a-b73b-d5b63aec2eaa # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8865e342-f28b-4c4d-9985-7c89efb7c0a9
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 93138bc1-2302-43a6-9b1c-b56ea371b7c9
        userCondition: null
handle: blog
hasTitleField: true
icon: null
name: Blog
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
