color: null
fieldLayouts:
  79762d97-b1b7-4ff5-b054-43514fdf6480:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-13T05:24:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3e544b8-88bf-4761-8df2-d767fa1502b7 # Text
            handle: headline
            includeInCards: false
            instructions: null
            label: Headline
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a51a0ba2-a74f-4def-ae2c-db19692231d6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-13T05:24:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3e544b8-88bf-4761-8df2-d767fa1502b7 # Text
            handle: subheadline
            includeInCards: false
            instructions: null
            label: Subheadline
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86b6a858-f878-4c24-a7ea-e7b096a452ee
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-13T05:24:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7f0dd947-99d8-4456-93f3-4ce4f6162a3f # Rich Text - Simple
            handle: copy
            includeInCards: false
            instructions: null
            label: Copy
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 34c61dc7-2418-411a-aabf-ce5cd877df8a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-13T05:24:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 27614c47-5513-4551-beb1-347205d45a65 # Case Study Blocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6289f919-6ecb-4b6b-ae2c-9df711edee40
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 546f6f65-46b7-4ba2-bd34-92e62cab8f2a
        userCondition: null
handle: caseStudy
hasTitleField: false
icon: null
name: 'Case Study'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{ headline|length ? headline : ''Case Study'' }'
titleTranslationKeyFormat: null
titleTranslationMethod: site
