color: null
fieldLayouts:
  aabeb06e-710a-410e-bc39-0d3ed9e66bbb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-13T05:21:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3e544b8-88bf-4761-8df2-d767fa1502b7 # Text
            handle: overline
            includeInCards: false
            instructions: null
            label: Overline
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db2ab5e6-258b-4173-b689-68e0f56e0f4f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-13T05:21:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3e544b8-88bf-4761-8df2-d767fa1502b7 # Text
            handle: headline
            includeInCards: false
            instructions: null
            label: Headline
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9242ffe5-dae8-4851-92b9-49ed44a1bd9a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-13T05:21:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7f0dd947-99d8-4456-93f3-4ce4f6162a3f # Rich Text - Simple
            handle: copy
            includeInCards: false
            instructions: null
            label: Copy
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 45d3f58f-cb42-418d-8b7f-1f287796fc67
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-13T05:21:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6d792fe4-471d-48ed-bc45-5fe112ba7e46 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 45cd075c-9def-42ea-9170-88700c9154d8
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-05-13T05:21:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3b93f659-b09a-43f2-9ff4-39c540342ede # Lightswitch - Default Off
            handle: flushImage
            includeInCards: false
            instructions: null
            label: 'Flush Image?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fe563dcb-447a-4603-a717-6e663c6a218a
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-05-13T05:21:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 923d8646-3be2-4308-9885-6a849083e88b # Image Position - L/R
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 377b9214-ded8-4058-9b07-95501163dd09
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 6743b353-37a0-49ac-902c-5d1ce10f7e77
        userCondition: null
handle: caseStudyBlock
hasTitleField: false
icon: null
name: 'Case Study Block'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{ headline }'
titleTranslationKeyFormat: null
titleTranslationMethod: site
