color: null
fieldLayouts:
  b4e61546-6a88-4e8e-ad23-f557f7b3a255:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-13T00:09:17+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Question
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d2c40d3c-9ac6-4d6c-a686-852e6d5102e9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-13T00:10:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 42eea3c2-2f84-43d8-a495-647d4994a8d5 # Text - Multiline
            handle: answer
            includeInCards: false
            instructions: null
            label: Answer
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83433c1b-1e22-43be-8286-4dd8275c54cc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7adec12d-8c50-4a25-b866-5aa3459223b4
        userCondition: null
handle: faq
hasTitleField: true
icon: null
name: FAQ
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
