color: null
fieldLayouts:
  2081ff81-2629-48c6-b983-1297d2cfdb1b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-14T02:36:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3e544b8-88bf-4761-8df2-d767fa1502b7 # Text
            handle: headline
            includeInCards: false
            instructions: null
            label: Headline
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c029c8bc-8fb2-4d25-b222-11b305848215
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-14T02:37:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 49cf21f8-8ce0-456c-82dc-b6a0445dc171 # FAQ Selector
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b831f4c-aa10-4351-be04-b8ecfc757007
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 492a6bb4-a640-4350-888b-818f12b1b909
        userCondition: null
handle: faqs
hasTitleField: false
icon: null
name: FAQs
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{ headline|length ? headline : ''FAQ Selector'' }'
titleTranslationKeyFormat: null
titleTranslationMethod: site
