color: null
fieldLayouts:
  460a0dd2-09dc-46a6-91c6-381e2bfadd9d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-13T03:36:45+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3e544b8-88bf-4761-8df2-d767fa1502b7 # Text
            handle: headline
            includeInCards: false
            instructions: null
            label: Headline
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af045013-6d4e-4893-9795-0af1610f2eaf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-13T03:36:45+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 42eea3c2-2f84-43d8-a495-647d4994a8d5 # Text - Multiline
            handle: copy
            includeInCards: false
            instructions: null
            label: Copy
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 627f882e-42b7-44ed-a986-be76a7a0f38a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-13T03:36:45+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6d792fe4-471d-48ed-bc45-5fe112ba7e46 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 984c8ab9-6d92-47ca-9dd5-54a534107ea6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-13T03:42:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: da9f3d8e-5ba9-4eb9-a423-6ea09ddaed21 # Form
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99fd1ce0-2633-444d-ad2a-9d137f7b90a1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0626413c-9354-47a3-855f-0d6984f1d8bb
        userCondition: null
handle: formEmbed
hasTitleField: false
icon: null
name: 'Form Embed'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{ headline }'
titleTranslationKeyFormat: null
titleTranslationMethod: site
