color: null
fieldLayouts:
  71660a2a-5e9c-456e-9584-e81e70baf6f2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-12T23:30:47+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0cf026d5-6d08-4e27-8a1f-ab30bca41c98
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-13T05:01:50+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9023f06b-9ae7-4baa-942f-8a2a1ebe07cd # Hero
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 192b2944-adf7-40b2-ae82-264859eb8757
            userCondition: null
            warning: null
            width: 100
        name: Hero
        uid: 0102572d-d127-40b1-b9c0-704387cc932f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-13T05:35:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 69b71247-c0c6-4339-b528-2d8b66d72119 # Page Builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 29473306-da38-457c-881d-d1aa1298c707
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 31f7cff5-21a8-46b9-a155-96d874d43ae7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-13T05:35:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 453f9294-407d-405a-b73b-d5b63aec2eaa # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96c7cc2a-9548-4c86-be76-7662764c5657
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 90708b4c-cfa0-42da-8d0c-6e17859647c9
        userCondition: null
handle: genericPage
hasTitleField: true
icon: file
name: 'Generic Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
