color: null
fieldLayouts:
  99a47eb9-c58a-4f3b-9b9b-1ab6cc321a1e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-13T05:26:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3e544b8-88bf-4761-8df2-d767fa1502b7 # Text
            handle: headline
            includeInCards: false
            instructions: null
            label: Headline
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6111ef9-af9d-421b-b5e2-abdfa301e0df
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-13T05:26:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0b199c11-0b79-4e4b-b931-f9c85e23a667 # Link / Button
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eb5c9db4-e561-478f-b113-bbb417dcbde8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-14T04:06:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: afc81e04-cd3e-4112-970d-6969f8f40b8f # CTA Background
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db65674f-fd3a-4bff-a209-d54c17b8eb3f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-14T04:06:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3b93f659-b09a-43f2-9ff4-39c540342ede # Lightswitch - Default Off
            handle: splitFade
            includeInCards: false
            instructions: null
            label: 'Split Fade?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2bae8446-f3f8-47c9-98f6-f26c686df656
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-14T04:12:59+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: fa59b73c-4193-4d7e-a42a-2bda6d535687 # Lightswitch - Default On
            handle: includeCalendly
            includeInCards: false
            instructions: null
            label: 'Include Calendly?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3890eaff-a68f-4254-869f-14974e0447ac
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 01799d7b-b854-41b6-bbb7-01ccf41cfde0
        userCondition: null
handle: inlineCallToAction
hasTitleField: false
icon: null
name: 'Inline Call to Action'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{ headline }'
titleTranslationKeyFormat: null
titleTranslationMethod: site
