color: null
fieldLayouts:
  30c8cbb5-b367-42bd-9ba5-43e9ff5e9e21:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-13T05:22:29+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3e544b8-88bf-4761-8df2-d767fa1502b7 # Text
            handle: headline
            includeInCards: false
            instructions: null
            label: Headline
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 06eea48e-579b-4faf-8f27-bc61ec45d6a4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-13T05:22:29+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7f0dd947-99d8-4456-93f3-4ce4f6162a3f # Rich Text - Simple
            handle: copy
            includeInCards: false
            instructions: null
            label: Copy
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 458ee091-c671-4c6f-a3ce-329bf77c6160
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 846e168c-7d15-48c7-83b7-7b9734eecc3f
        userCondition: null
handle: sectionHeader
hasTitleField: false
icon: null
name: 'Section Header'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{ headline }'
titleTranslationKeyFormat: null
titleTranslationMethod: site
