color: null
fieldLayouts:
  d07b2890-ffe9-45d1-b05a-8b5826daf95d:
    cardView:
      - 'layoutElement:40ff6818-2efd-4978-831d-67c115a6bbb9'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-14T01:10:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3e544b8-88bf-4761-8df2-d767fa1502b7 # Text
            handle: headline
            includeInCards: false
            instructions: null
            label: Headline
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e2c6c20-07b1-43ea-9979-9082bfb4d09c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-14T01:27:03+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7f0dd947-99d8-4456-93f3-4ce4f6162a3f # Rich Text - Simple
            handle: copy
            includeInCards: false
            instructions: null
            label: Copy
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3373fb57-85c6-4e21-87d8-fbf8ff55526f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-14T01:10:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6d792fe4-471d-48ed-bc45-5fe112ba7e46 # Image
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 40ff6818-2efd-4978-831d-67c115a6bbb9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 28b198ed-dd80-4d4c-94af-561883a268ab
        userCondition: null
handle: splitContentHero
hasTitleField: false
icon: null
name: 'Split Content Hero'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{ headline }'
titleTranslationKeyFormat: null
titleTranslationMethod: site
