color: null
fieldLayouts:
  89bb6ace-a9b9-473a-97b0-7599378af0be:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-14T02:24:17+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3e544b8-88bf-4761-8df2-d767fa1502b7 # Text
            handle: headline
            includeInCards: false
            instructions: null
            label: Headline
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 03f2710d-2df7-4016-be5f-551a0a74f8b1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-14T02:24:17+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3e544b8-88bf-4761-8df2-d767fa1502b7 # Text
            handle: subheadline
            includeInCards: false
            instructions: null
            label: Subheadline
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a5ca4f7b-1b29-480a-b67d-1abd7c92d362
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-14T02:24:17+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7f0dd947-99d8-4456-93f3-4ce4f6162a3f # Rich Text - Simple
            handle: copy
            includeInCards: false
            instructions: null
            label: Copy
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 17fcdfdb-3c9b-4b58-9a9c-697ad6085511
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-14T02:24:17+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6d792fe4-471d-48ed-bc45-5fe112ba7e46 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 962bd3c9-ec22-4fab-bad6-7fd773c9c146
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-05-14T02:24:17+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 923d8646-3be2-4308-9885-6a849083e88b # Image Position - L/R
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 40d7cc5c-5f8a-4304-8a9c-605916804590
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-05-14T19:16:39+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3b93f659-b09a-43f2-9ff4-39c540342ede # Lightswitch - Default Off
            handle: flushImage
            includeInCards: false
            instructions: null
            label: 'Flush Image?'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b533259-8044-43ab-b697-49a6d58d01c6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 34ff6f5c-d8dd-4c0f-a4a1-351d119aadb4
        userCondition: null
handle: splitContent
hasTitleField: false
icon: null
name: 'Split Content'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{ headline }'
titleTranslationKeyFormat: null
titleTranslationMethod: site
