color: null
fieldLayouts:
  b8271af4-0ec7-4c07-a3a3-4bc7fc06592b:
    cardView:
      - 'layoutElement:83841a15-d1aa-4007-9083-09e1bfb55ab7'
      - 'layoutElement:3d14da98-2e1e-43c4-8143-751b64bbd4fd'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-12T23:48:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ad2dc7f1-4844-41d2-9ace-604b607b1789
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-12T23:50:40+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3e544b8-88bf-4761-8df2-d767fa1502b7 # Text
            handle: position
            includeInCards: true
            instructions: null
            label: Position
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83841a15-d1aa-4007-9083-09e1bfb55ab7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-12T23:50:40+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7f0dd947-99d8-4456-93f3-4ce4f6162a3f # Rich Text - Simple
            handle: biography
            includeInCards: false
            instructions: null
            label: Biography
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 55dbf67d-5f24-42cc-aaa8-c5029fbcce65
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-12T23:50:40+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6d792fe4-471d-48ed-bc45-5fe112ba7e46 # Image
            handle: headshot
            includeInCards: true
            instructions: null
            label: Headshot
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3d14da98-2e1e-43c4-8143-751b64bbd4fd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8163caf1-0591-4a19-a59e-d7e86b87a753
        userCondition: null
handle: teamMember
hasTitleField: true
icon: null
name: 'Team Member'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
