color: null
fieldLayouts:
  11fe5bbd-6a15-42d5-9258-df3211a0a544:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-13T05:27:10+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a8787df3-5236-487b-9f1e-b3f25f6ac187 # Testimonial Selector
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2472c5a8-7caf-4361-8ea5-fac01584fa2f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 745064ef-00f3-4c8c-a21b-4b6efbbf7753
        userCondition: null
handle: testimonials
hasTitleField: false
icon: null
name: Testimonials
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: 'Testimonial Block'
titleTranslationKeyFormat: null
titleTranslationMethod: site
