color: null
fieldLayouts:
  3ec67360-3fd3-40e2-bb47-3cfc76d290fc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-13T00:47:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7f0dd947-99d8-4456-93f3-4ce4f6162a3f # Rich Text - Simple
            handle: copy
            includeInCards: false
            instructions: null
            label: Copy
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 31f532cb-63f2-4e61-86ac-86e942a5620f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3558090f-1bbd-440c-ba25-8b99224aa0a2
        userCondition: null
handle: textBlock
hasTitleField: false
icon: null
name: 'Text Block'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: 'Blog Content'
titleTranslationKeyFormat: null
titleTranslationMethod: site
