columnSuffix: null
handle: form
instructions: null
name: Form
searchable: false
settings:
  forms: '*'
translationKeyFormat: null
translationMethod: none
type: Solspace\Freeform\FieldTypes\FormFieldType
