columnSuffix: null
handle: linkButton
instructions: 'If left blank, will include a "Join Our Community" button'
name: 'Link / Button'
searchable: false
settings:
  advancedFields:
    - target
    - ariaLabel
  fullGraphqlData: false
  maxLength: 255
  showLabelField: true
  typeSettings:
    __assoc__:
      -
        - asset
        -
          __assoc__:
            -
              - allowedKinds
              - '*'
            -
              - showUnpermittedVolumes
              - ''
            -
              - showUnpermittedFiles
              - ''
      -
        - entry
        -
          __assoc__:
            -
              - sources
              -
                - 'section:7b662bcd-ea91-4c91-86ce-c60348c664d1' # Pages
                - 'section:d8298ca5-3785-4f41-bd3f-909cc81b5a4a' # Blog
            -
              - showUnpermittedSections
              - '1'
            -
              - showUnpermittedEntries
              - '1'
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - ''
            -
              - allowAnchors
              - '1'
            -
              - allowCustomSchemes
              - ''
  types:
    - entry
    - url
    - asset
    - category
    - email
    - tel
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
