defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 46729116-829d-4657-98cc-5502f96b590a # Category
handle: blogCategories
maxAuthors: 1
name: 'Blog Categories'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  08c386f4-5a41-4c9f-8282-f6785af06bfc: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: _sections/blogCategory/category.twig
    uriFormat: 'blog/{slug}'
type: channel
