defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 6fe413ae-c734-4aed-b954-95093d371dac # FAQ
handle: faqs
maxAuthors: 1
name: FAQs
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  08c386f4-5a41-4c9f-8282-f6785af06bfc: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
