defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 03d163a9-dbe0-4797-9f55-a00fe30985bb # Team Member
handle: team
maxAuthors: 1
name: Team
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  08c386f4-5a41-4c9f-8282-f6785af06bfc: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: a35cc533-81cf-4c55-b564-cb6bdc5da521
type: structure
