defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: d28ac774-ff3f-4f08-aaee-4c7dd13f1b55 # Testimonial
handle: testimonials
maxAuthors: 1
name: Testimonials
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  08c386f4-5a41-4c9f-8282-f6785af06bfc: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 7226783d-fd60-4f18-8db2-74b2d9ef237c
type: structure
